controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    
vypisPostavy:
    path: /vypisPostavy
    controller: App\Controller\PostavaController::vypisPostavy
